apiVersion: v2
name: 'crossplane'
description: A Helm chart for wrapping crossplane
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: 'crossplane'
    version: '1.18.2'
    repository: "https://charts.crossplane.io/stable"
