---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: default
spec:
  encryptedData:
    password.txt: AQCTpy1mLwB6oEnsAiB9dkjWhjs9dIOWDOq5JyzgAONtGgqwlXPO0gZNk7YUdKBVJdcjbewV76QQ3cmNoQG0vDw2oINe7wKVqj1OnH1l3Xwd7zr1ywwnW3HKR3D/zQz450X17F/Ww64sbNpEU622njxeMhHWTIbnM5t7zzVoALT9H8pSmftyAvElmdY7XeWookECj7qtFPYIZlSZ6xieCKsI2qmAvW/kUzE3BYg7oEfk4nUq8e2gjPjXRoYEbVYubNgolToECYr9tZzPvnc13slXpsYFIiXhcD0Lh3nhZLfp8zc/FjqalRIFqBNlFl8iZFUjRA9FUVlIioGaOSZWZbwcOketK6qXZNW37GiKXeaPRxV79kC3n+l4PJxD7zTM2DCZMDKG2kEKtbo=
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: default
