apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  destination:
    namespace: dagster
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        dagster:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            host: dagster.k8s.localhost
            tls:
              enabled: true
              secretName: tls-secret
      valueFiles:
      - values.yaml
    path: config/apps/dagster
    repoURL: https://github.com/hagzag/just-do-it.git
    targetRevision: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true