apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
    spec:
      containers:
      - name: app-container
        image: ubuntu:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done;"]
        volumeMounts:
        - name: s3-storage
          mountPath: /data # Replace with your desired mount path
      volumes:
      - name: s3-storage
        persistentVolumeClaim:
          claimName: s3-pvc-devlelopers-bucket
      # tolerations:
      #   - key: CriticalAddonsOnly
      #     value: "true"
      #     operator: Equal
      #     effect: NoExecute
      #   - key: CriticalAddonsOnly
      #     value: "true"
      #     operator: Equal
      #     effect: NoSchedule
