apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-devlelopers-bucket
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3
  csi:
    driver: s3.csi.aws.com
    volumeHandle: devlelopers-bucket
    volumeAttributes:
      bucketName: devlelopers-bucket
      mountOptions: "--dir-mode=0777 --file-mode=0666"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc-devlelopers-bucket
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3
  resources:
    requests:
      storage: 5Gi
  volumeName: s3-pv-devlelopers-bucket
