apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization

resources:
  - root-ca.yaml

namespace: cert-manager

commonAnnotations:
  reloader.stakater.com/auto: "true"

secretGenerator:
  - name: local-rootca
    files:
      - tls.crt
      - tls.key
generatorOptions:
  disableNameSuffixHash: true