---
version: '3'

includes:
  
  aws-sso: ./suites/aws-sso/Taskfile.yaml
  iac: ./suites/terraform/Taskfile.yaml
  k3d: ./suites/k3d-playground/Taskfile.yaml
  production-rediness-external-dns: ./suites/production-rediness-series/external-dns/Taskfile.yaml
  git-workflow: ./suites/git-workkflow/Taskfile.yaml
  git: ./suites/git-workkflow/git.yaml
  coredns: ./suites/coredns/Taskfile.yaml
  pre-commit: ./suites/pre-commit/Taskfile.yaml
  vault: ./suites/vault-eso/Taskfile.yaml
  awx: ./suites/awx/Taskfile.yaml
  goldilocks: ./suites/goldilocks/Taskfile.yaml
  gatekeeper: ./suites/gatekeeper/Taskfile.yaml
  gatekeeper-pm: ./suites/gatekeeper-policy-manager/Taskfile.yaml
  bitwarden: ./suites/bitwarden/Taskfile.yaml
  crossplane: ./suites/crossplane/Taskfile.yaml
  actions-runner-controller: ./suites/actions-runner-controller/Taskfile.yaml
  k6: ./suites/k6/Taskfile.yaml
