apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketAccessControl
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketaccesscontrol
  labels:
    testing.upbound.io/example-name: bucket-access-control
  name: bucket-access-control
spec:
  forProvider:
    bucketRef:
      name: crossplane-bucket-demo
    entity: allUsers
    role: READER
